CREATE TYPE "RegistrationStep" AS ENUM ('STARTED','PRIVACY_NOTICE','CHANNEL_OPT_IN','AI_PREFERENCE','NAME','PAYMENT_INSTRUCTIONS','PAYMENT_REVIEW','COMPLETE');
ALTER TABLE "students" ADD COLUMN "registration_step" "RegistrationStep" NOT NULL DEFAULT 'STARTED';
ALTER TABLE "payments" ADD COLUMN "review_note" TEXT;
